In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('StudentPerformanceFactors.csv')
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [4]:
df['Distance_from_Home'].unique()

array(['Near', 'Moderate', 'Far', nan], dtype=object)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6607 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [5]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [7]:
df['Teacher_Quality'].unique()

array(['Medium', 'High', 'Low', nan], dtype=object)

In [8]:
df['Teacher_Quality']=df['Teacher_Quality'].fillna(df['Teacher_Quality'].mode()[0])

In [9]:
df.iloc[:,11]

0       Medium
1       Medium
2       Medium
3       Medium
4         High
         ...
6602    Medium
6603      High
6604    Medium
6605    Medium
6606    Medium
Name: Teacher_Quality, Length: 6607, dtype: object

In [10]:
df['Teacher_Quality'].isnull().sum()

np.int64(0)

In [12]:
df['Distance_from_Home']=df['Distance_from_Home'].fillna(df['Distance_from_Home'].mode()[0])

In [13]:
df['Parental_Education_Level']=df['Parental_Education_Level'].fillna(df['Parental_Education_Level'].mode()[0])

In [14]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [18]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['Low','Medium','High']])
df['Parental_Involvement']=encoder.fit_transform(df[['Parental_Involvement']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,0.0,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,1.0,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,0.0,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,1.0,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [19]:
df['Access_to_Resources']=encoder.fit_transform(df[['Access_to_Resources']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,2.0,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,0.0,1.0,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,1.0,1.0,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,0.0,1.0,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,1.0,1.0,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [20]:
df['Motivation_Level']=encoder.fit_transform(df[['Motivation_Level']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [21]:
df['Family_Income']=encoder.fit_transform(df[['Family_Income']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,0.0,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,1.0,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,1.0,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,1.0,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,1.0,High,Public,Neutral,4,No,College,Near,Female,70

In [23]:
df['Teacher_Quality']=encoder.fit_transform(df[['Teacher_Quality']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,...,1.0,Public,Positive,3,No,High School,Near,Male,67,1.0
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,...,1.0,Public,Negative,4,No,College,Moderate,Female,61,1.0
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,...,1.0,Public,Neutral,4,No,Postgraduate,Near,Male,74,1.0
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,...,1.0,Public,Negative,4,No,High School,Moderate,Male,71,1.0
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,...,2.0,Public,Neutral,4,No,College,Near,Female,70,2.0

In [24]:
df['Distance_from_Home'].unique()

array(['Near', 'Moderate', 'Far'], dtype=object)

In [28]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['Near','Moderate','Far']])
df['Distance_from_Home']=encoder.fit_transform(df[['Distance_from_Home']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,...,1.0,Public,Positive,3,No,High School,0.0,Male,67,1.0
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,...,1.0,Public,Negative,4,No,College,1.0,Female,61,1.0
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,...,1.0,Public,Neutral,4,No,Postgraduate,0.0,Male,74,1.0
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,...,1.0,Public,Negative,4,No,High School,1.0,Male,71,1.0
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,...,2.0,Public,Neutral,4,No,College,0.0,Female,70,2.0

In [30]:
df['Parental_Education_Level'].unique()

array(['High School', 'College', 'Postgraduate'], dtype=object)

In [31]:
encoder=OrdinalEncoder(categories=[['High School', 'College', 'Postgraduate']])
df['Parental_Education_Level']=encoder.fit_transform(df[['Parental_Education_Level']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,...,1.0,Public,Positive,3,No,0.0,0.0,Male,67,1.0
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,...,1.0,Public,Negative,4,No,1.0,1.0,Female,61,1.0
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,...,1.0,Public,Neutral,4,No,2.0,0.0,Male,74,1.0
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,...,1.0,Public,Negative,4,No,0.0,1.0,Male,71,1.0
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,...,2.0,Public,Neutral,4,No,1.0,0.0,Female,70,2.0

In [34]:
df['Peer_Influence'].unique()

array(['Positive', 'Negative', 'Neutral'], dtype=object)

In [35]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['Negative','Neutral','Positive']])
df['Peer_Influence']=encoder.fit_transform(df[['Peer_Influence']])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,...,1.0,Public,2.0,3,No,0.0,0.0,Male,67,1.0
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,...,1.0,Public,0.0,4,No,1.0,1.0,Female,61,1.0
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,...,1.0,Public,1.0,4,No,2.0,0.0,Male,74,1.0
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,...,1.0,Public,0.0,4,No,0.0,1.0,Male,71,1.0
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,...,2.0,Public,1.0,4,No,1.0,0.0,Female,70,2.0

In [36]:
df=pd.get_dummies(df,columns=['School_Type'])
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t,School_Type_Private,School_Type_Public
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,...,2.0,3,No,0.0,0.0,Male,67,1.0,False,True
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,...,0.0,4,No,1.0,1.0,Female,61,1.0,False,True
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,...,1.0,4,No,2.0,0.0,Male,74,1.0,False,True
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,...,0.0,4,No,0.0,1.0,Male,71,1.0,False,True
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,...,1.0,4,No,1.0,0.0,Female,70,2.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,2.0,1.0,No,7,76,1.0,Yes,1,...,2.0,2,No,0.0,0.0,Female,68,1.0,False,True
6603,23,76,2.0,1.0,No,8,81,1.0,Yes,3,...,2.0,2,No,0.0,0.0,Female,69,2.0,False,True
6604,20,90,1.0,0.0,Yes,6,65,0.0,Yes,3,...,0.0,2,No,2.0,0.0,Female,68,1.0,False,True
6605,10,86,2.0,2.0,Yes,6,91,2.0,Yes,2,...,2.0,3,No,0.0,2.0,Female,68,1.0,True,False
6606,15,67,1.0,0.0,Yes,9,94,1.0,Yes,0,...,2.0,4,No,2.0,0.0,Male,64,1.0,False,True

In [37]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t,School_Type_Private,School_Type_Public
0,23,84,0.0,2.0,No,7,73,0.0,Yes,0,...,2.0,3,No,0.0,0.0,1,67,1.0,False,True
1,19,64,0.0,1.0,No,8,59,0.0,Yes,2,...,0.0,4,No,1.0,1.0,0,61,1.0,False,True
2,24,98,1.0,1.0,Yes,7,91,1.0,Yes,2,...,1.0,4,No,2.0,0.0,1,74,1.0,False,True
3,29,89,0.0,1.0,Yes,8,98,1.0,Yes,1,...,0.0,4,No,0.0,1.0,1,71,1.0,False,True
4,19,92,1.0,1.0,Yes,6,65,1.0,Yes,3,...,1.0,4,No,1.0,0.0,0,70,2.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,2.0,1.0,No,7,76,1.0,Yes,1,...,2.0,2,No,0.0,0.0,0,68,1.0,False,True
6603,23,76,2.0,1.0,No,8,81,1.0,Yes,3,...,2.0,2,No,0.0,0.0,0,69,2.0,False,True
6604,20,90,1.0,0.0,Yes,6,65,0.0,Yes,3,...,0.0,2,No,2.0,0.0,0,68,1.0,False,True
6605,10,86,2.0,2.0,Yes,6,91,2.0,Yes,2,...,2.0,3,No,0.0,2.0,0,68,1.0,True,False
6606,15,67,1.0,0.0,Yes,9,94,1.0,Yes,0,...,2.0,4,No,2.0,0.0,1,64,1.0,False,True

In [38]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Extracurricular_Activities']=le.fit_transform(df['Extracurricular_Activities'])

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Internet_Access']=le.fit_transform(df['Internet_Access'])
df['Learning_Disabilities']=le.fit_transform(df['Learning_Disabilities'])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Teacher_Quality\t,School_Type_Private,School_Type_Public
0,23,84,0.0,2.0,0,7,73,0.0,1,0,...,2.0,3,0,0.0,0.0,1,67,1.0,False,True
1,19,64,0.0,1.0,0,8,59,0.0,1,2,...,0.0,4,0,1.0,1.0,0,61,1.0,False,True
2,24,98,1.0,1.0,1,7,91,1.0,1,2,...,1.0,4,0,2.0,0.0,1,74,1.0,False,True
3,29,89,0.0,1.0,1,8,98,1.0,1,1,...,0.0,4,0,0.0,1.0,1,71,1.0,False,True
4,19,92,1.0,1.0,1,6,65,1.0,1,3,...,1.0,4,0,1.0,0.0,0,70,2.0,False,True

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   float64
 3   Access_to_Resources         6607 non-null   float64
 4   Extracurricular_Activities  6607 non-null   int64
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   float64
 8   Internet_Access             6607 non-null   int64
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   float64
 11  Teacher_Quality             6607 non-null   float64
 12  Peer_Influence              6607 non-null   float64
 13  Physical_Activity           6607 non-null   int64
 14  Learning_Disabilities       6607 non-null   int64
 15  Parental_Education_Level    6607 non-null   float64
 16  Distance_from_Home          6607 non-null   float64
 17  Gender                      6607 non-null   int64
 18  Exam_Score                  6607 non-null   int64
 19  Teacher_Quality	            6607 non-null   float64
 20  School_Type_Private         6607 non-null   bool
 21  School_Type_Public          6607 non-null   bool
dtypes: bool(2), float64(9), int64(11)
memory usage: 1.0 MB

In [49]:
X=df.drop(columns=['Exam_Score'])
y=df['Exam_Score']

In [50]:
df['Exam_Score'].isnull().sum()

np.int64(0)

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [52]:
y.shape

(6607,)

In [53]:
X.shape

(6607, 21)

In [54]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)

In [56]:
from sklearn.metrics import mean_absolute_error,r2_score
print('MAE:',mean_absolute_error(y_test,y_pred))
print("R2 Score",r2_score(y_test,y_pred))

MAE: 0.44428945627208283
R2 Score 0.7709282415480216