In [36]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [37]:
source=requests.get('https://books.toscrape.com')
source

In [38]:
soup=BeautifulSoup(source.text,"html.parser")
print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [39]:
books=soup.find_all("article",class_="product_pod")
print(len(books))

20

In [40]:
book=books[0]
for i in soup.find_all('h3'):
    print(i.text.strip())

A Light in the ...
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History ...
The Requiem Red
The Dirty Little Secrets ...
The Coming Woman: A ...
The Boys in the ...
The Black Maria
Starving Hearts (Triangular Trade ...
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little ...
Rip it Up and ...
Our Band Could Be ...
Olio
Mesaerion: The Best Science ...
Libertarianism for Beginners
It's Only the Himalayas

In [41]:
ratings=soup.find_all('p',class_="star-rating One")
print(len(ratings))

6

In [42]:
for book in books:
    title=book.h3.a["title"]
    price=book.find("p",class_="price_color").text
    rating=book.find("p")["class"][1]
    availability= book.find("p",class_="instock availability").text.strip()
    image_link=book.find("img")["src"]
    print(title,price,rating,availability,image_link)

A Light in the Attic Â£51.77 Three In stock media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg
Tipping the Velvet Â£53.74 One In stock media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg
Soumission Â£50.10 One In stock media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg
Sharp Objects Â£47.82 Four In stock media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg
Sapiens: A Brief History of Humankind Â£54.23 Five In stock media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg
The Requiem Red Â£22.65 One In stock media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg
The Dirty Little Secrets of Getting Your Dream Job Â£33.34 Four In stock media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull Â£17.93 Three In stock media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics Â£22.60 Four In stock media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg
The Black Maria Â£52.15 One In stock media/cache/58/46/5846057e28022268153beff6d352b06c.jpg
Starving Hearts (Triangular Trade Trilogy, #1) Â£13.99 Two In stock media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg
Shakespeare's Sonnets Â£20.66 Four In stock media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg
Set Me Free Â£17.46 Five In stock media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) Â£52.29 Five In stock media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg
Rip it Up and Start Again Â£35.02 Five In stock media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 Â£57.25 Three In stock media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg
Olio Â£23.88 One In stock media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg
Mesaerion: The Best Science Fiction Stories 1800-1849 Â£37.59 One In stock media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg
Libertarianism for Beginners Â£51.33 Two In stock media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg
It's Only the Himalayas Â£45.17 Two In stock media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg

In [48]:
data=[]
for page in  range(1,4):
    url=f"https://books.toscrape.com/catalogue/page-{page}.html"
    source=requests.get(url)
    soup=BeautifulSoup(source.text,"html.parser")
    books=soup.find_all("article",class_="product_pod")
    for book in books:
        title=book.h3.a["title"]
        price=book.find("p",class_="price_color").text
        rating=book.find("p")["class"][1]
        availability= book.find("p",class_="instock availability").text.strip()
        product_link=book.h3.a["href"]
        image_link=book.find("img")["src"]
        data.append({
        "Title":title,
        "Price":price,
        "Rating":rating,
        "Availability":availability,
        "Product link":product_link,
        "Image Link":image_link})
df=pd.DataFrame(data)
df

,Title,Price,Rating,Availability,Product link,Image Link
0,A Light in the Attic,Â£51.77,Three,In stock,a-light-in-the-attic_1000/index.html,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...
1,Tipping the Velvet,Â£53.74,One,In stock,tipping-the-velvet_999/index.html,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...
2,Soumission,Â£50.10,One,In stock,soumission_998/index.html,../media/cache/3e/ef/3eef99c9d9adef34639f51066...
3,Sharp Objects,Â£47.82,Four,In stock,sharp-objects_997/index.html,../media/cache/32/51/3251cf3a3412f53f339e42cac...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,sapiens-a-brief-history-of-humankind_996/index...,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...
5,The Requiem Red,Â£22.65,One,In stock,the-requiem-red_995/index.html,../media/cache/68/33/68339b4c9bc034267e1da611a...
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,Four,In stock,the-dirty-little-secrets-of-getting-your-dream...,../media/cache/92/27/92274a95b7c251fea59a2b8a7...
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,In stock,the-coming-woman-a-novel-based-on-the-life-of-...,../media/cache/3d/54/3d54940e57e662c4dd1f3ff00...
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,In stock,the-boys-in-the-boat-nine-americans-and-their-...,../media/cache/66/88/66883b91f6804b2323c836933...
9,The Black Maria,Â£52.15,One,In stock,the-black-maria_991/index.html,../media/cache/58/46/5846057e28022268153beff6d...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,In stock,starving-hearts-triangular-trade-trilogy-1_990...,../media/cache/be/f4/bef44da28c98f905a3ebec0b8...
11,Shakespeare's Sonnets,Â£20.66,Four,In stock,shakespeares-sonnets_989/index.html,../media/cache/10/48/1048f63d3b5061cd2f424d20b...
12,Set Me Free,Â£17.46,Five,In stock,set-me-free_988/index.html,../media/cache/5b/88/5b88c52633f53cacf162c15f4...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,Five,In stock,scott-pilgrims-precious-little-life-scott-pilg...,../media/cache/94/b1/94b1b8b244bce9677c2f29ccc...
14,Rip it Up and Start Again,Â£35.02,Five,In stock,rip-it-up-and-start-again_986/index.html,../media/cache/81/c4/81c4a973364e17d01f217e118...
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock,our-band-could-be-your-life-scenes-from-the-am...,../media/cache/54/60/54607fe8945897cdcced00441...
16,Olio,Â£23.88,One,In stock,olio_984/index.html,../media/cache/55/33/553310a7162dfbc2c6d19a84d...
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock,mesaerion-the-best-science-fiction-stories-180...,../media/cache/09/a3/09a3aef48557576e1a85ba7ef...
18,Libertarianism for Beginners,Â£51.33,Two,In stock,libertarianism-for-beginners_982/index.html,../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52...
19,It's Only the Himalayas,Â£45.17,Two,In stock,its-only-the-himalayas_981/index.html,../media/cache/27/a5/27a53d0bb95bdd88288eaf66c...
20,In Her Wake,Â£12.84,One,In stock,in-her-wake_980/index.html,../media/cache/5d/72/5d72709c6a7a9584a4d1cf076...
21,How Music Works,Â£37.32,Two,In stock,how-music-works_979/index.html,../media/cache/5c/c8/5cc8e107246cb478960d4f0ab...
22,Foolproof Preserving: A Guide to Small Batch J...,Â£30.52,Three,In stock,foolproof-preserving-a-guide-to-small-batch-ja...,../media/cache/9f/59/9f59f01fa916a7bb8f0b28a40...
23,Chase Me (Paris Nights #2),Â£25.27,Five,In stock,chase-me-paris-nights-2_977/index.html,../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994f...
24,Black Dust,Â£34.53,Five,In stock,black-dust_976/index.html,../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4...
25,Birdsong: A Story in Pictures,Â£54.64,Three,In stock,birdsong-a-story-in-pictures_975/index.html,../media/cache/af/6e/af6e796160fe63e0cf19d4439...
26,America's Cradle of Quarterbacks: Western Penn...,Â£22.50,Three,In stock,americas-cradle-of-quarterbacks-western-pennsy...,../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb...
27,Aladdin and His Wonderful Lamp,Â£53.13,Three,In stock,aladdin-and-his-wonderful-lamp_973/index.html,../media/cache/d6/da/d6da0371958068bbaf39ea9c1...
28,Worlds Elsewhere: Journeys Around Shakespeareâ...,Â£40.30,Five,In stock,worlds-elsewhere-journeys-around-shakespeares-...,../media/cache/2e/98/2e98c332bf8563b5847849715...
29,Wall and Piece,Â£44.18,Four,In stock,wall-and-piece_971/index.html,../media/cache/a5/41/a5416b9646aaa7287baa287ec...
30,The Four Agreements: A Practical Guide to Pers...,Â£17.66,Five,In stock,the-four-agreements-a-practical-guide-to-perso...,../media/cache/0f/7e/0f7ee69495c0df1d35723f012...
31,The Five Love Languages: How to Express Heartf...,Â£31.05,Three,In stock,the-five-love-languages-how-to-express-heartfe...,../media/cache/38/c5/38c56fba316c07305643a8065...
32,The Elephant Tree,Â£23.82,Five,In stock,the-elephant-tree_968/index.html,../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe...
33,The Bear and the Piano,Â£36.89,One,In stock,the-bear-and-the-piano_967/index.html,../media/cache/cf/bb/cfbb5e62715c6d888fd07794c...
34,Sophie's World,Â£15.94,Five,In stock,sophies-world_966/index.html,../media/cache/65/71/6571919836ec51ed54f0050c3...
35,Penny Maybe,Â£33.29,Three,In stock,penny-maybe_965/index.html,../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5...
36,Maude (1883-1993):She Grew Up with the country,Â£18.02,Two,In stock,maude-1883-1993she-grew-up-with-the-country_96...,../media/cache/f5/88/f5889d038f5d8e949b494d147...
37,"In a Dark, Dark Wood",Â£19.63,One,In stock,in-a-dark-dark-wood_963/index.html,../media/cache/23/85/238570a1c284e730dbc737a7e...
38,Behind Closed Doors,Â£52.22,Four,In stock,behind-closed-doors_962/index.html,../media/cache/e1/5c/e15c289ba58cea38519e1281e...
39,You can't bury them all: Poems,Â£33.63,Two,In stock,you-cant-bury-them-all-poems_961/index.html,../media/cache/e9/20/e9203b733126c4a0832a1c788...
40,Slow States of Collapse: Poems,Â£57.31,Three,In stock,slow-states-of-collapse-poems_960/index.html,../media/cache/72/41/72417db983862010ef0c1a25d...
41,Reasons to Stay Alive,Â£26.41,Two,In stock,reasons-to-stay-alive_959/index.html,../media/cache/cb/bd/cbbdb0222ee8a0f6ab6165741...
42,Private Paris (Private #10),Â£47.61,Five,In stock,private-paris-private-10_958/index.html,../media/cache/9d/05/9d0533bae1578846d728a8291...
43,#HigherSelfie: Wake Up Your Life. Free Your So...,Â£23.11,Five,In stock,higherselfie-wake-up-your-life-free-your-soul-...,../media/cache/9c/46/9c463c7631c82401160fd3b55...
44,Without Borders (Wanderlove #1),Â£45.07,Two,In stock,without-borders-wanderlove-1_956/index.html,../media/cache/24/e2/24e2f5c9d325c4004d8190c05...
45,When We Collided,Â£31.77,One,In stock,when-we-collided_955/index.html,../media/cache/08/04/08044269fc197645268a6197c...
46,"We Love You, Charlie Freeman",Â£50.27,Five,In stock,we-love-you-charlie-freeman_954/index.html,../media/cache/5f/15/5f152afdbc42356ecba02f610...
47,Untitled Collection: Sabbath Poems 2014,Â£14.27,Four,In stock,untitled-collection-sabbath-poems-2014_953/ind...,../media/cache/f9/3b/f93b4a650f03a5d21f2436d78...
48,"Unseen City: The Majesty of Pigeons, the Discr...",Â£44.18,Four,In stock,unseen-city-the-majesty-of-pigeons-the-discree...,../media/cache/41/a2/41a20f35adf0caea24f208dc0...
49,Unicorn Tracks,Â£18.78,Three,In stock,unicorn-tracks_951/index.html,../media/cache/76/8e/768ea5924ac1ef6297c2be995...
50,"Unbound: How Eight Technologies Made Us Human,...",Â£25.52,One,In stock,unbound-how-eight-technologies-made-us-human-t...,../media/cache/4a/3b/4a3b055f9e378a95fedbef55e...
51,Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRo...,Â£16.28,One,In stock,tsubasa-world-chronicle-2-tsubasa-world-chroni...,../media/cache/36/df/36df4caaf1420b1183a823535...
52,Throwing Rocks at the Google Bus: How Growth B...,Â£31.12,Three,In stock,throwing-rocks-at-the-google-bus-how-growth-be...,../media/cache/03/86/038650c9e7517b4baf2a423cd...
53,This One Summer,Â£19.49,Four,In stock,this-one-summer_947/index.html,../media/cache/c4/dd/c4ddd9ced89966b0602ec85e0...
54,Thirst,Â£17.27,Five,In stock,thirst_946/index.html,../media/cache/c4/0a/c40a64f59e7487b1a80a049f6...
55,The Torch Is Passed: A Harding Family Story,Â£19.09,One,In stock,the-torch-is-passed-a-harding-family-story_945...,../media/cache/33/e5/33e507172541628acfd421503...
56,The Secret of Dreadwillow Carse,Â£56.13,One,In stock,the-secret-of-dreadwillow-carse_944/index.html,../media/cache/c4/a2/c4a2a1a026c67bcceb5a411c7...
57,The Pioneer Woman Cooks: Dinnertime: Comfort C...,Â£56.41,One,In stock,the-pioneer-woman-cooks-dinnertime-comfort-cla...,../media/cache/b7/f4/b7f4843dbe062d44be1ffcfa1...
58,The Past Never Ends,Â£56.50,Four,In stock,the-past-never-ends_942/index.html,../media/cache/89/b8/89b850edb01851a91f64ba114...
59,The Natural History of Us (The Fine Art of Pre...,Â£45.22,Three,In stock,the-natural-history-of-us-the-fine-art-of-pret...,../media/cache/5d/7f/5d7f496cdf5e5962a73ecdcc1...

In [49]:
df.sample()

,Title,Price,Rating,Availability,Product link,Image Link
46,"We Love You, Charlie Freeman",Â£50.27,Five,In stock,we-love-you-charlie-freeman_954/index.html,../media/cache/5f/15/5f152afdbc42356ecba02f610...

In [50]:
df.to_csv("books.csv",index=False)