In [6]:
import pandas as pd
import requests

In [14]:
url =  "https://live-oil-prices.p.rapidapi.com/web-crawling/api/oil-price-charts"

headers = {
    "Content-Type": "application/json",
    "X-RapidAPI-Host":"live-oil-prices.p.rapidapi.com",
    "X-RapidAPI-Key":"d3e2c10462mshfeeeb1c9f2b6cc4p191ab2jsn079d958c7eb2"
}

response = requests.get(url, headers=headers)

df=pd.DataFrame(response.json())
df

,headerName,flag,name,last,change,percentChange,lastUpdated
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay)
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay)
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay)
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay)
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay)
...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price)
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price)
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price)
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price)
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price)

In [20]:
df.columns=["category","flag_url","commodity_name","current_price","price_change","percent_change","update_info"]

In [21]:
df

,category,flag_url,commodity_name,current_price,price_change,percent_change,update_info
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay)
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay)
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay)
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay)
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay)
...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price)
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price)
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price)
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price)
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price)

In [22]:
df["percent_change_clean"]=(df["percent_change"].str.extract(r'([+-]?\d+\.\d+)').astype(float))

In [23]:
df["delay_minutes"]=(df["update_info"].str.extract(r'(\d+)'))

In [29]:
df

,category,flag_url,commodity_name,current_price,price_change,percent_change,update_info,percent_change_clean,delay_minutes
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay),2.24,10.0
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay),1.81,10.0
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay),3.15,15.0
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay),2.70,10.0
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay),0.47,10.0
...,...,...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price),0.00,NaN
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price),0.00,NaN
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price),64.25,NaN
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price),59.63,NaN
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price),41.65,NaN

In [31]:
def category(name):
    if "Crude" in name:
        return "Crude Oil"
    elif "Gas" in name:
        return "Natural Gas"
    elif "Gasoline" in name:
        return "Refined Fuel"
    else:
        return "Other"
df["commodity_type"]=df["commodity_name"].apply(category)

In [32]:
df

,category,flag_url,commodity_name,current_price,price_change,percent_change,update_info,percent_change_clean,delay_minutes,commodity_type
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay),2.24,10.0,Crude Oil
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay),1.81,10.0,Crude Oil
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay),3.15,15.0,Crude Oil
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay),2.70,10.0,Natural Gas
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay),0.47,10.0,Natural Gas
...,...,...,...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price),64.25,NaN,Other
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price),59.63,NaN,Other
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price),41.65,NaN,Other

In [34]:
region_map={
    "WTI Crude":"USA",
    "Brent Crude":"Europe",
    "Murban Crude":"UAE",
    "Iran Heavy":"IRAN"
}
df["region"]=df["commodity_name"].map(region_map)

In [35]:
df

,category,flag_url,commodity_name,current_price,price_change,percent_change,update_info,percent_change_clean,delay_minutes,commodity_type,region
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay),2.24,10.0,Crude Oil,USA
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay),1.81,10.0,Crude Oil,Europe
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay),3.15,15.0,Crude Oil,UAE
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay),2.70,10.0,Natural Gas,NaN
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay),0.47,10.0,Natural Gas,NaN
...,...,...,...,...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other,IRAN
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other,NaN
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price),64.25,NaN,Other,NaN
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price),59.63,NaN,Other,NaN
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price),41.65,NaN,Other,NaN

In [36]:
df.drop(columns=['region'],inplace=True)

In [37]:
df

,category,flag_url,commodity_name,current_price,price_change,percent_change,update_info,percent_change_clean,delay_minutes,commodity_type
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay),2.24,10.0,Crude Oil
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay),1.81,10.0,Crude Oil
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay),3.15,15.0,Crude Oil
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay),2.70,10.0,Natural Gas
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay),0.47,10.0,Natural Gas
...,...,...,...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price),64.25,NaN,Other
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price),59.63,NaN,Other
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price),41.65,NaN,Other

In [38]:
def volatility(x):
    if abs(x)>5:
        return "High"
    elif abs(x)>2:
        return "Medium"
    return "Low"
df["volatility"]=df["percent_change_clean"].apply(volatility)

In [39]:
df

,category,flag_url,commodity_name,current_price,price_change,percent_change,update_info,percent_change_clean,delay_minutes,commodity_type,volatility
0,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,WTI Crude,107.78,+2.36,+2.24(10-Minute Delay),(10-Minute Delay),2.24,10.0,Crude Oil,Medium
1,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Brent Crude,111.24,+1.98,+1.81(10-Minute Delay),(10-Minute Delay),1.81,10.0,Crude Oil,Low
2,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban Crude,108.00,+3.30,+3.15(15-Minute Delay),(15-Minute Delay),3.15,15.0,Crude Oil,Medium
3,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Natural Gas,3.040,+0.080,+2.7(10-Minute Delay),(10-Minute Delay),2.70,10.0,Natural Gas,Medium
4,Futures & Indexes,https://d32r1sh890xpii.cloudfront.net/flag_ima...,Gasoline,3.719,+0.017,+0.47(10-Minute Delay),(10-Minute Delay),0.47,10.0,Natural Gas,Low
...,...,...,...,...,...,...,...,...,...,...,...
139,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Iran Heavy,124.10,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other,Low
140,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Kuwait Export,124.25,+0.00,+0.00(March. Price),(March. Price),0.00,NaN,Other,Low
141,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Merey,85.92,+33.61,+64.25(March. Price),(March. Price),64.25,NaN,Other,High
142,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Murban,110.86,+41.41,+59.63(March. Price),(March. Price),59.63,NaN,Other,High
143,OPEC Members(Monthly Pricing),https://d32r1sh890xpii.cloudfront.net/flag_ima...,Saharan Blend,104.24,+30.65,+41.65(March. Price),(March. Price),41.65,NaN,Other,High

In [40]:
df.shape

(144, 11)

In [41]:
df.to_csv('Global Live Oil Prices Dataset')