In [1]:
import pandas as pd

In [2]:
data=[1,2,3,4]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
import pandas as pd
data=[1,2,3,4]
id=['a','b','c','d']
series=pd.Series(data,id)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
df=pd.DataFrame([[1,2,3],[6,7,9],[10,11,12]])
print(df)

    0   1   2
0   1   2   3
1   6   7   9
2  10  11  12

In [5]:
df=pd.DataFrame([[1,2,3],[6,7,9]],columns=['a','b','c'],index=[1,2])
print(df)

   a  b  c
1  1  2  3
2  6  7  9

In [6]:
obesity_data=pd.read_csv('obesity.csv')
obesity_data.head #first five data

<bound method NDFrame.head of    Country  Year  Gender Age_Group  Average_BMI  Obesity_Rate_Percent
0    India  2020    Male     18-25         23.1                   8.5
1    India  2020  Female     18-25         22.8                   7.9
2    India  2020    Male     26-40         24.6                  12.3
3    India  2020  Female     26-40         25.1                  14.2
4    India  2021    Male     18-25         23.4                   9.1
5    India  2021  Female     18-25         23.0                   8.6
6      USA  2020    Male     18-25         26.5                  21.4
7      USA  2020  Female     18-25         25.9                  19.8
8      USA  2020    Male     26-40         28.1                  29.6
9      USA  2020  Female     26-40         27.8                  31.2
10      UK  2021    Male     26-40         27.2                  24.5
11      UK  2021  Female     26-40         26.9                  26.1>

In [7]:
obesity_data.tail()

   Country  Year  Gender Age_Group  Average_BMI  Obesity_Rate_Percent
7      USA  2020  Female     18-25         25.9                  19.8
8      USA  2020    Male     26-40         28.1                  29.6
9      USA  2020  Female     26-40         27.8                  31.2
10      UK  2021    Male     26-40         27.2                  24.5
11      UK  2021  Female     26-40         26.9                  26.1

In [8]:
obesity_data.sample(10,random_state=59)

   Country  Year  Gender Age_Group  Average_BMI  Obesity_Rate_Percent
2    India  2020    Male     26-40         24.6                  12.3
9      USA  2020  Female     26-40         27.8                  31.2
11      UK  2021  Female     26-40         26.9                  26.1
4    India  2021    Male     18-25         23.4                   9.1
6      USA  2020    Male     18-25         26.5                  21.4
8      USA  2020    Male     26-40         28.1                  29.6
3    India  2020  Female     26-40         25.1                  14.2
10      UK  2021    Male     26-40         27.2                  24.5
0    India  2020    Male     18-25         23.1                   8.5
5    India  2021  Female     18-25         23.0                   8.6

In [9]:
obesity_data.columns.tolist()

['Country',
 'Year',
 'Gender',
 'Age_Group',
 'Average_BMI',
 'Obesity_Rate_Percent']

In [10]:
list(obesity_data.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [11]:
obesity_data.shape

(12, 6)

In [12]:
obesity_data.size #rows*columns

72

In [13]:
obesity_data.describe()

              Year  Average_BMI  Obesity_Rate_Percent
count    12.000000    12.000000             12.000000
mean   2020.333333    25.366667             17.766667
std       0.492366     1.966230              8.725963
min    2020.000000    22.800000              7.900000
25%    2020.000000    23.325000              8.975000
50%    2020.000000    25.500000             17.000000
75%    2021.000000    26.975000             24.900000
max    2021.000000    28.100000             31.200000

In [14]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               12 non-null     object
 1   Year                  12 non-null     int64
 2   Gender                12 non-null     object
 3   Age_Group             12 non-null     object
 4   Average_BMI           12 non-null     float64
 5   Obesity_Rate_Percent  12 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 708.0+ bytes

***Acessing Data***

In [15]:
obesity_data.loc[0,'Age_Group']

'18-25'

###loc-label based indexing (access a group of rows and columns by label(s)

In [ ]:
import pandas as pd
obesity_data=pd.read_csv('obesity.csv')
obesity_data.loc[0:10,"Age_Group"]

In [17]:
obesity_data.loc[0:10,["Age_Group","Country","Year"]]

   Age_Group Country  Year
0      18-25   India  2020
1      18-25   India  2020
2      26-40   India  2020
3      26-40   India  2020
4      18-25   India  2021
5      18-25   India  2021
6      18-25     USA  2020
7      18-25     USA  2020
8      26-40     USA  2020
9      26-40     USA  2020
10     26-40      UK  2021

In [18]:
obesity_data.loc[0:10,"Country":"Age_Group"]

   Country  Year  Gender Age_Group
0    India  2020    Male     18-25
1    India  2020  Female     18-25
2    India  2020    Male     26-40
3    India  2020  Female     26-40
4    India  2021    Male     18-25
5    India  2021  Female     18-25
6      USA  2020    Male     18-25
7      USA  2020  Female     18-25
8      USA  2020    Male     26-40
9      USA  2020  Female     26-40
10      UK  2021    Male     26-40

In [19]:
obesity_data.loc[:,"Country":"Age_Group"]

   Country  Year  Gender Age_Group
0    India  2020    Male     18-25
1    India  2020  Female     18-25
2    India  2020    Male     26-40
3    India  2020  Female     26-40
4    India  2021    Male     18-25
5    India  2021  Female     18-25
6      USA  2020    Male     18-25
7      USA  2020  Female     18-25
8      USA  2020    Male     26-40
9      USA  2020  Female     26-40
10      UK  2021    Male     26-40
11      UK  2021  Female     26-40

In [20]:
obesity_data.loc[5:,"Country":"Age_Group"]

   Country  Year  Gender Age_Group
5    India  2021  Female     18-25
6      USA  2020    Male     18-25
7      USA  2020  Female     18-25
8      USA  2020    Male     26-40
9      USA  2020  Female     26-40
10      UK  2021    Male     26-40
11      UK  2021  Female     26-40

###iloc-purely integer based indexing for selection by position

In [21]:
obesity_data.iloc[0:10,[0,1,2]]

  Country  Year  Gender
0   India  2020    Male
1   India  2020  Female
2   India  2020    Male
3   India  2020  Female
4   India  2021    Male
5   India  2021  Female
6     USA  2020    Male
7     USA  2020  Female
8     USA  2020    Male
9     USA  2020  Female

In [22]:
obesity_data.iloc[[3,4,5],[0,1,2]]

  Country  Year  Gender
3   India  2020  Female
4   India  2021    Male
5   India  2021  Female

In [23]:
obesity_data.at[2,"Age_Group"]

'26-40'

In [24]:
obesity_data.at[0:2,"Age_Group"]//will throw error because we can't do slicing with at and iat

SyntaxError: unterminated string literal (detected at line 1) (3757470617.py, line 1)

In [ ]:
obesity_data.iat[0,0]

In [ ]:
obesity_data["Age_Group"]//accesing only for a column

In [ ]:
obesity_data.Country

In [ ]:
obesity_data[["Country","Year","Age_Group"]]

##Filtering Data##

In [ ]:
obesity_data.loc[obesity_data["Average_BMI"]>26]

In [ ]:
obesity_data.loc[(obesity_data["Year"]>2020)&(obesity_data["Country"]=="India")]

In [ ]:
obesity_data.loc[obesity_data["Country"].str.contains('UK')]

In [ ]:
obesity_data[obesity_data["Country"].str.contains('UK')]

##Updating Data

In [ ]:
obesity_data.loc[0,"Country"]="UK"

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.loc[:,"Gender"]="Male"

In [ ]:
obesity_data.tail()

In [ ]:
obesity_data.loc[[1,7],"Country"]="UK"

In [ ]:
obesity_data.head()

In [ ]:
obesity_data[:]

In [ ]:
obesity_data.iloc[1,4]=20

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.at[2,"Gender"]="Female"

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.iat[2,0]="NaN"

In [ ]:
obesity_data.head()

In [ ]:
obesity_data["Year"]="Null"

In [ ]:
obesity_data[:]

In [ ]:
def increment_bmi(x):
    return x+5
obesity_data["Average_BMI"]=obesity_data["Average_BMI"].apply(increment_bmi)
obesity_data["Average_BMI"]

In [ ]:
obesity_data["Average_BMI"]=obesity_data["Average_BMI"].apply(lambda x:x-5)

In [ ]:
obesity_data["Average_BMI"]

##Addinng a column

In [ ]:
obesity_data["Age_Group"]=obesity_data["Obesity_Rate_Percent"].apply(lambda x:"Young" if x<25 else "Old")

In [ ]:
obesity_data[:]

In [ ]:
import numpy as np
obesity_data["New Age Category"]=np.where(obesity_data["Average_BMI"]<20,"Over","Under")

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.insert(2,"Smoke","No")

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.drop(columns="Smoke")

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.drop(columns=["Age_Group","Smoke"],inplace=True)

In [ ]:
obesity_data[:]

In [ ]:
obesity_data=obesity_data.drop(columns="Year")

In [ ]:
obesity_data.head()

In [ ]:
del obesity_data["Gender"]

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.rename(columns={"Obesity_Rate_Percent":"Obesity_Rate"})

In [ ]:
obesity_data.rename(columns={"Country":"Origin","New Age Category":"Age"})

In [ ]:
obesity_data.head()

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':["Deepika","Jakiya","Likky","Meghna"]
})
df2=pd.DataFrame({
    'id':[3,4,5,6],
    'course':["GenAI","PHP","GO","RUST"]
})
inner_result=pd.merge(df1,df2,how='inner',on='id')
inner_result

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':["Deepika","Jakiya","Likky","Meghna"]
})
df2=pd.DataFrame({
    'id':[1,2,3,4],
    'course':["GenAI","NaN","GO","RUST"]
})
inner_result=pd.merge(df1,df2,how='inner',on='id')
inner_result

In [ ]:
outer_result=pd.merge(df1,df2,how='outer',on='id')
outer_result

In [ ]:
left_result=pd.merge(df1,df2,how='left',on='id')
left_result

In [ ]:
right_result=pd.merge(df1,df2,how='right',on='id')
right_result

In [ ]:
import pandas as pd
obesity_data=pd.read_csv('obesity.csv')
df3=pd.DataFrame({
    'id1':[1,2,3,4],
    'name':['Arjun','Deepu','Murali','Keerthy']
})
df4=pd.DataFrame({
    'id2':[3,4,5,6],
    'course':['Product','GenAI','CMA','CA']
})
inner_result=pd.merge(df3,df4,how='inner',left_on='id1',right_on='id2')
inner_result

In [ ]:
df3=pd.DataFrame({
    'id1':[1,2,3,4],
    'name':['Arjun','Deepu','Murali','Keerthy']
})
df4=pd.DataFrame({
    'id2':[3,4,5,6],
    'course':['Product','GenAI','CMA','CA']
})
result=pd.concat([df3,df4],axis=0)
result

In [ ]:
df3=pd.DataFrame({
    'id1':[1,2,3,4],
    'name':['Arjun','Deepu','Murali','Keerthy']
})
df4=pd.DataFrame({
    'id2':[3,4,5,6],
    'course':['Product','GenAI','CMA','CA']
})
result=pd.concat([df3,df4],axis=0,ignore_index=True)
result

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':["Deepika","Jakiya","Likky","Meghna"]
})
df2=pd.DataFrame({
    'id':[1,2,3,4],
    'course':["GenAI","NaN","GO","RUST"]
})
result2=pd.concat([df1,df2],axis=1)
result2

In [ ]:
result3=pd.concat([df1,df2],axis=0,keys=['df1','df2'])
result3

###Handling null values

In [ ]:
result3.isna()

In [ ]:
result3.notna()

In [ ]:
result3.isna().sum()

In [ ]:
obesity_data.isna().sum()

In [ ]:
obesity_data.notna().sum()

In [ ]:
import numpy as np
obesity_data.loc[0,'Age_Group']=np.nan
obesity_data.loc[0,'Year']=np.nan
obesity_data.loc[4,'Country']=np.nan

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.fillna(0,inplace=True)
obesity_data.head()

In [ ]:
import numpy as np
obesity_data.loc[0,'Age_Group']=np.nan
obesity_data.loc[0,'Year']=np.nan
obesity_data.loc[4,'Country']=np.nan

In [ ]:
obesity_data.head()

In [ ]:
obesity_data.loc[0,'Obesity_Rate_Percent']=np.nan

In [ ]:
obesity_data.head()

In [ ]:
obesity_data['Age_Group']=obesity_data['Age_Group'].fillna(30)

In [ ]:
obesity_data['Obesity_Rate_Percent']=obesity_data['Obesity_Rate_Percent'].fillna(obesity_data['Obesity_Rate_Percent'].mean())

In [ ]:
obesity_data.head()

In [ ]:
obesity_data['Year']=obesity_data['Year'].fillna(obesity_data['Year'].interpolate())

In [ ]:
obesity_data.head()